// Generated by CoffeeScript 1.12.7
(function() {
  var check, generaNumeri, generaNumero, indovinati, j, k, l, len, len1, len2, len3, m, num_lotto, num_utente, numeri_lotto, numeri_utente, soldi, txtLotto, txtUtente, userBet;

  soldi = prompt("Inserisci quanto vuoi scommettere");

  userBet = prompt("Numeri scommessi:");

  check = function(list) {
    var i, newList, thisValue;
    newList = [];
    i = 0;
    while (i < list.length) {
      thisValue = list[i];
      if (i > 0) {
        if (newList.indexOf(thisValue) > -1) {
          true;
        }
      }
      newList.push(thisValue);
      i++;
    }
    return false;
  };

  generaNumero = function() {
    return Number(Math.floor(Math.random() * 90) + 1);
  };

  generaNumeri = function() {
    var i, j, numeri, numero;
    numeri = [];
    for (i = j = 1; j <= 20; i = ++j) {
      numero = generaNumero();
      numeri.push(numero);
    }
    if (!check(numeri)) {
      return numeri.sort();
    } else {
      return generaNumeri();
    }
  };

  numeri_lotto = generaNumeri();

  numeri_utente = userBet.split(',');

  indovinati = 0;

  for (j = 0, len = numeri_utente.length; j < len; j++) {
    num_utente = numeri_utente[j];
    for (k = 0, len1 = numeri_lotto.length; k < len1; k++) {
      num_lotto = numeri_lotto[k];
      if (Number(num_utente) === num_lotto) {
        indovinati++;
      }
    }
  }

  alert("Hai indovinato " + indovinati + " numeri! Hai vinto " + soldi * indovinati + " euro.");

  txtLotto = "";

  for (l = 0, len2 = numeri_lotto.length; l < len2; l++) {
    num_lotto = numeri_lotto[l];
    txtLotto += num_lotto + "|| ";
  }

  txtUtente = "";

  for (m = 0, len3 = numeri_utente.length; m < len3; m++) {
    num_utente = numeri_utente[m];
    txtUtente += num_utente + "|| ";
  }

  document.getElementById("generati").innerHTML = txtLotto;

  document.getElementById("user").innerHTML = txtUtente;

}).call(this);
